name: Verify Changed files
description: Find files that were modified during workflow execution.
author: jackton1
inputs:
  files:
    description: List of files to check for changes.
    required: true
  autocrlf:
    description: Modify the core.autocrlf setting possible values (true, false, input)
    default: 'input'
    required: true
  separator:
    description: 'Split character for array output'
    required: true
    default: " "

outputs:
  files_changed:
    description: Boolean indicating that files have changed.
    value: ${{ steps.verify-changed-files.outputs.files_changed }}
  changed_files:
    description: List of changed files
    value: ${{ steps.verify-changed-files.outputs.changed_files }}

runs:
  using: 'composite'
  steps:
    - name: Glob match
      uses: tj-actions/glob@v9
      id: glob
      with:
        files: ${{ inputs.files }}
        separator: "|"
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: verify-changed-files
      shell: bash
      env:
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_FILES: ${{ steps.glob.outputs.paths }}
        INPUT_AUTO_CRLF: ${{ inputs.autocrlf }}
        INPUT_SEPARATOR: ${{ inputs.separator }}

branding:
  icon: file-text
  color: white
