name: Verify Changed files
description: Find files that were modified during workflow execution.
author: jackton1
inputs:
  token:
    description: GITHUB_TOKEN or a repo scoped PAT
    required: true
    default: ${{ github.token }}
  files:
    description: List of files to check for changes.
    required: true
  autocrlf:
    description: Modify the core.autocrlf setting possible values (true, false, input)
    default: 'input'
    required: true

outputs:
  files_changed:
    description: Boolean indicating that files have changed.
    value: ${{ steps.verify-changed-files.outputs.files_changed }}
  changed_files:
    description: List of changed files
    value: ${{ steps.verify-changed-files.outputs.changed_files }}

runs:
  using: 'composite'
  steps:
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: verify-changed-files
      shell: bash
      env:
        PLATFORM: ${{ runner.os }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_AUTO_CRLF: ${{ inputs.autocrlf }}

branding:
  icon: file-text
  color: white
