name: Verify Changed files
description: Find files that were modified during workflow execution.
author: jackton1
inputs:
  files:
    description: 'File/Directory names to check for uncommited changes.'
    required: false
  files-separator:
    description: 'Separator used to split the `files` input'
    default: "\n"
    required: false
  autocrlf:
    description: 'Modify the git config [core.autocrlf](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf).'
    default: 'input'
    required: false
  separator:
    description: 'Output string separator.'
    required: false
    default: " "

outputs:
  files_changed:
    description: Boolean indicating that files have changed.
    value: ${{ steps.verify-changed-files.outputs.files_changed }}
  changed_files:
    description: List of changed files
    value: ${{ steps.verify-changed-files.outputs.changed_files }}

runs:
  using: 'composite'
  steps:
    - name: Glob match
      uses: tj-actions/glob@cebfb084cdf62d72c5318b1b3595ac5a45ed022f # renovate: tag=v16.11
      id: glob
      with:
        files: ${{ inputs.files }}
        files-separator: ${{ inputs.files-separator }}
        separator: "|"
        match-directories: false
        match-gitignore-files: true
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: verify-changed-files
      shell: bash
      env:
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_FILES_PATTERN_FILE: ${{ steps.glob.outputs.paths-output-file }}
        INPUT_AUTO_CRLF: ${{ inputs.autocrlf }}
        INPUT_SEPARATOR: ${{ inputs.separator }}

branding:
  icon: file-text
  color: white
