name: Update release version.
on:
  release:
    types: [published]


jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Sync release version.
        uses: tj-actions/sync-release-version@v8.7
        id: sync-release-version
        with:
          pattern: '${{ github.repository }}@'
          paths: |
            README.md
      - name: Generate CHANGELOG
        uses: tj-actions/github-changelog-generator@v1.8
        with:
          output: 'HISTORY.md'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          base: "main"
          title: "Upgraded to ${{ steps.sync-release-version.outputs.new_version }}"
          branch: "upgrade-to-${{ steps.sync-release-version.outputs.new_version }}"
          commit-message: "Upgraded from ${{ steps.sync-release-version.outputs.old_version }} -> ${{ steps.sync-release-version.outputs.new_version }}"
          body: "View [CHANGES](https://github.com/${{ github.repository }}/compare/${{ steps.sync-release-version.outputs.old_version }}...${{ steps.sync-release-version.outputs.new_version }})"
          token: ${{ secrets.PAT_TOKEN }}
