name: Format README.md

on:
  push:
    branches:
      - main

jobs:
  sync-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Run auto-doc
        uses: tj-actions/auto-doc@b10ceedffd794ec29a8fa8700529f40c1b64a951 # v3.6.0
        with:
          use_code_blocks: true
          use_major_version: true
          use_tag_commit_hash: true

      - name: Run test
        uses: tj-actions/remark@10fc40701928cbafcc4a2d241679579d218144ff # v3

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@9437562cb29a5a1120dd9f02cc760ec9e5d4651a # v20.0.2
        id: verify_changed_files
        with:
          files: |
            README.md

      - name: README.md changed
        if: steps.verify_changed_files.outputs.files_changed == 'true'
        run: |
          echo "README.md has uncommitted changes"
          exit 1

      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          base: "main"
          labels: "merge when passing"
          title: "Updated README.md"
          branch: "chore/update-readme"
          commit-message: "Updated README.md"
          body: "Updated README.md"
          token: ${{ secrets.PAT_TOKEN }}
